// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpJiVrXzxmTonYQ1wG2SkaztsncJzC-SI',
    appId: '1:105873807479:web:8e709990be45edb9458e72',
    messagingSenderId: '105873807479',
    projectId: 'dict-attendance-form',
    authDomain: 'dict-attendance-form.firebaseapp.com',
    storageBucket: 'dict-attendance-form.appspot.com',
    measurementId: 'G-3PVVTFCK7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALmUkRV1WaKrgA_iyOeP1bbo7Zix1GDRE',
    appId: '1:105873807479:android:7190fb4cc5f7af2f458e72',
    messagingSenderId: '105873807479',
    projectId: 'dict-attendance-form',
    storageBucket: 'dict-attendance-form.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7bQNg1EB6g6mAvnIzALiAZeSbXJtke5k',
    appId: '1:105873807479:ios:3ce2bb194e055ab4458e72',
    messagingSenderId: '105873807479',
    projectId: 'dict-attendance-form',
    storageBucket: 'dict-attendance-form.appspot.com',
    iosBundleId: 'com.example.attendanceWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7bQNg1EB6g6mAvnIzALiAZeSbXJtke5k',
    appId: '1:105873807479:ios:164dbee4a4aade02458e72',
    messagingSenderId: '105873807479',
    projectId: 'dict-attendance-form',
    storageBucket: 'dict-attendance-form.appspot.com',
    iosBundleId: 'com.example.attendanceWebApp.RunnerTests',
  );
}
